timezone: Europe/London
permalink: date
encoding: utf-8
company_name: Coldtap
company_address: "Suite 5, 4 Blenheim Court, Peppercorn Close, Peterborough, PE1 2DU"
company_registration_details: "Registered in England and Wales #6632696"
url: "https://coldtap.net"
plugins:
  - jekyll-sitemap
